apiVersion: v1
data:
  credentials.json: ${AZURE_B64ENCODED_CREDENTIALS}
kind: Secret
metadata:
  name: inlets-access-key
type: Opaque
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: inlets-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inlets-operator
  template:
    metadata:
      labels:
        app: inlets-operator
      annotations:
        prometheus.io.scrape: "false"
    spec:
      serviceAccountName: inlets-operator
      containers:
      - name: operator
        image: jpangms/inlets-operator:0.2.6
        #image: alexellis/inlets-operator:0.2.6
        imagePullPolicy: Always
        command:
          - ./inlets-operator
          - "-provider=azure"
          - "-region=westus2"
          - "-project-id=<reusing for azure subscription id... for now>"
          # - "-provider=digitalocean"
          # - "-provider=packet"
          # - "-project-PACKET-ID"
          - "-access-key-file=/var/secrets/inlets/inlets-access-key"
        env:
        - name: client_image
          value: alexellis2/inlets:2.5.0
        - name: AZURE_AUTH_LOCATION
          value: /var/secrets/inlets/credentials.json
        resources:
          limits:
            memory: 128Mi
          requests:
            memory: 25Mi
        volumeMounts:
        - mountPath: /var/secrets/inlets/
          name: inlets-access-key
          readOnly: true
      volumes:
      - name: inlets-access-key
        secret:
          defaultMode: 420
          secretName: inlets-access-key
